

import numpy as np
import lasagne



TIMESTAMP_FORMAT_STR = '%Y-%m-%d %H:%M:%S'



# EEG setup-related
#CHANNEL_NAMES = ['FC3', 'FCz', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP5', 'CPz', 'CP6', 'P3', 'Pz', 'P4']
FREQ_S_CSV = 128.0
FREQ_S_BDF = 2048.0
#NUM_CHANNELS_CSV = 128 #16
NUM_CHANNELS_BDF = 128
LEN_INITIAL_DATA = 128
AMP_WAIT_SEC = 0.01
LEN_DATA_CHUNK_READ = 16.0
LEN_RIGHT_SEC = 5.0
LEN_LEFT_SEC = 5.0
LEN_IDLE_SEC = 5.0
LEN_PERIOD_SEC = LEN_IDLE_SEC + LEN_RIGHT_SEC + LEN_IDLE_SEC + LEN_LEFT_SEC
LEN_COLOR_CONV_SEC = 1.0
LEN_CALIB_SEC = LEN_PERIOD_SEC
LEN_REC_SEC = 10.0 * LEN_PERIOD_SEC
LEN_REC_BUF_SEC = 1.2 * LEN_REC_SEC


# Paradigm-related
#NUM_EVENT_TYPES_CSV = 3     # r, l, idle
EVENT_ID_RH = 0
EVENT_ID_LH = 1
EVENT_ID_IDLE = 2
LABEL_ID_RED = 17
NUM_EVENT_TYPES_BDF = 1     # button down
EVENT_LENGTH_SAMPLES = 512
FEAT_MULT_1_SIMU = 0.002
FEAT_MULT_2_SIMU = 1.0
FEAT_MULT_1_REAL = 0.001
FEAT_MULT_2_REAL = 1.0
IMAGE_W = 960
IMAGE_H = 640
#CURSOR_COLOR_REST = 'green'
#CURSOR_COLOR_RIGHT = 'red'
#CURSOR_COLOR_LEFT = 'blue'
#CURSOR_COLOR_IDLE = 'black'
CURSOR_COLOR_REST = np.array([0, 127, 0])    # RGB
CURSOR_COLOR_RIGHT = np.array([255, 0, 0])
CURSOR_COLOR_LEFT = np.array([0, 0, 255])
CURSOR_COLOR_IDLE = np.array([0, 0, 0])


# Signal proc
#DECIMATION_FACTOR_PREPROC = 2  # 128/2 = 64 => max freq is 32 Hz
#DECIMATION_FACTOR_NN = 1
#FREQ_S_DECIMATED = 32.0
#FREQ_CUT_LO = 8.0
#FREQ_CUT_HI = 30.0
#FREQ_TRANS_HZ = 0.5
#REREF_CHANNEL_ID = 1
#WINDOW_SIZE_RAW_SECS = 1.0
#WINDOW_SIZE_RAW_SAMPLES = int(WINDOW_SIZE_RAW_SECS * FREQ_S)
#WINDOW_SIZE_DECIMATED_SAMPLES = WINDOW_SIZE_RAW_SAMPLES / DECIMATION_FACTOR_PREPROC
#M_FIR = int(WINDOW_SIZE_DECIMATED_SAMPLES)
#LEN_PADDING = M_FIR / LEN_DATA_CHUNK_READ
MOVING_AVG_WINDOW_SIZE_SECS = 1.0
#LEN_EPOCH_DECIMATED_SAMPLES = int(4.0 * FREQ_S / DECIMATION_FACTOR_PREPROC)
#EPOCH_OFFSET_SAMPLES = -int(2.0 * FREQ_S / DECIMATION_FACTOR_PREPROC)
NUM_PARALLEL_JOBS = 4


# NN
#NUM_MAX_TRAIN_EPOCHS = 200
#NUM_TRAIN_DATA_INSTANCES = 64
NUM_MAX_TRAIN_EPOCHS = 50
NUM_TRAIN_DATA_INSTANCES = 1024   #1024
NUM_MAX_TRAIN_EPOCHS_RUNTEST = 10
NUM_TRAIN_DATA_INSTANCES_RUNTEST = 8
#VALIDATION_DATA_RATIO = 0.4
BATCH_SIZE = 32
INTERNAL_NONLINEARITY_CONV = lasagne.nonlinearities.linear
DROPOUT_PROBABILITY = 0.5
#MAXPOOL_SIZE = (2, 2)
NUM_DENSE_UNITS = 512
INTERNAL_NONLINEARITY_DENSE = lasagne.nonlinearities.rectify


# Cursor
CURSOR_STEP_MULT = 0.0
